### ISSUE TITLE
xTea for long reads cannot find some temporary files

### ISSUE THREAD

**Issue by mldmort** [parklab/xTea#22]
Hi,

I'm trying to run xTea on ONT long reads for a sample with 10x coverage and this is my batch file:
```
#!/bin/bash

#SBATCH --account=my_account
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=20
#SBATCH -t 1-0:0:0
#SBATCH --mem=32G
#SBATCH -p my_partition
#SBATCH -o 104_hg00733_%j.out
PREFIX=/my/prefix/
############
############
REF=/address/of/fasta/file/hg38.fasta
XTEA_PATH=/address/to/xtea_long/
BAM_LIST=${PREFIX}"bam_list.txt"
TMP=${PREFIX}"tmp/"
REP_LIB=/address/to/rep/libarary/xTea/data/
SVA_REF_COPY=null
############
############
python ${XTEA_PATH}"l_main.py" -C -b ${BAM_LIST} -r ${REF} -p ${TMP} -o ${PREFIX}"candidate_list_from_clip.txt"  -n 20 -w 75  
python ${XTEA_PATH}"l_main.py" -A -b ${BAM_LIST} -r ${REF} -p ${TMP} -i ${PREFIX}"candidate_list_from_clip.txt" -o ${PREFIX}"all_ins_seqs.fa" --rep ${REP_LIB} -n 20 
python ${XTEA_PATH}"l_main.py" -N -b ${BAM_LIST} -r ${REF} -p ${TMP}"ghost" -o ${PREFIX}"ghost_reads.fa" --rmsk /somthing/LINE/hg38/hg38_L1_larger_500_with_all_L1HS.out --cns /something/consensus/LINE1.fa --min 4000 -n 20
python ${XTEA_PATH}"l_main.py" -Y -i ${PREFIX}"all_ins_seqs.fa" -r ${REF} -p ${TMP}"classification" --rep ${REP_LIB} -y 15 -o ${PREFIX}"classified_results.txt" -n 20
python ${XTEA_PATH}"l_main.py" --clean -b ${BAM_LIST} -r ${REF} -p ${TMP} -i ${PREFIX}"candidate_list_from_clip.txt"  -n 20
```

It ran for about 6.5 hours but after that it stoped and gave me this error message:
```
Traceback (most recent call last):
  File ".../xTea/xtea_long/l_main.py", line 311, in <module>
    lrc.classify_ins_seqs(sf_rep_ins, sf_ref, flk_lenth, sf_rslt)
  File ".../xTea/xtea_long/l_rep_classification.py", line 139, in classify_ins_seqs
    polyA_masker.parse_polyA_from_algnmt(sf_algnmt, sf_ref, sf_tmp_out)
  File ".../xTea/xtea_long/l_polyA_masker.py", line 15, in parse_polyA_from_algnmt
    samfile = pysam.AlignmentFile(sf_algnmt, s_open_fmt)  # read in the sam file
  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 941, in pysam.libcalignmentfile.AlignmentFile._open
FileNotFoundError: [Errno 2] could not open alignment file `.../104_hg00733/tmp/classification/polyA_cns.bam`: No such file or directory
```

before this message there are multiple messages also with "Failed to open file" message for these files:
```
.../104_hg00733/tmp/classification/all_tei_seq_2_ref.bam
.../104_hg00733/tmp/classification/polyA_cns.bam
```

These seems to be temporary files.
Also I should mention that I didn't include option `-g` for gff3 file because it was not included in the example run for long reads, although it is listed as required options.

If you can please help me figure out the problem,
Thanks,
Milad

**Comment by simoncchu** [comment]
Not sure exactly why these polyA (as decoy) alignments are not generated. Could you send me these two files? I can test it. You can send me through github or email chong.simon.chu@gmail.com. If this cannot be shared, do you mind test on a HG002 CCS data? Just to make sure the configuration is correct.

**Comment by mldmort** [comment]
Hi,

I ran the program again and the only change I made was to increase the number of cores to use in the header:
```
#SBATCH --ntasks-per-node=60
```
but actually didn't change the `-n 20` parameter in the sbatch file, and it seems that the program finished. So I'm not sure what exactly happened. But I cannot find the gVCF result file anywhere. Where should the result file be?
These are the files generated in the running directory:
```
104_hg00733_6542942.err
104_hg00733_6542942.out
all_ins_seqs.fa
all_ins_seqs.fa.after_polyA_round.fa
all_ins_seqs.fa.after_polyA_round.fa.after_LINE1_round.fa
all_ins_seqs.fa.after_polyA_round.fa.after_LINE1_round.fa.after_ALU_round.fa
all_ins_seqs.fa.after_polyA_round.fa.after_LINE1_round.fa.after_ALU_round.fa.after_HERV_round.fa
all_ins_seqs.fa.after_polyA_round.fa.after_LINE1_round.fa.after_ALU_round.fa.after_HERV_round.fa.after_SVA_round.fa
all_ins_seqs.fa.for_pseudogene.fa
all_ins_seqs.fa.sites
bam_list1.txt
bam_list.txt
candidate_list_from_clip.txt
candidate_list_from_clip.txt_-1000.passed
candidate_list_from_clip.txt.-1000_to_asm_list.txt
candidate_list_from_clip.txt_1500.passed
candidate_list_from_clip.txt.1500_to_asm_list.txt
candidate_list_from_clip.txt_3500.passed
candidate_list_from_clip.txt.3500_to_asm_list.txt
candidate_list_from_clip.txt_500.passed
candidate_list_from_clip.txt.500_to_asm_list.txt
candidate_list_from_clip.txt.left_breakponts
candidate_list_from_clip.txt.right_breakponts
classified_results.txt.ALU.txt
classified_results.txt.ALU.txt_to_be_decided_cases.txt
classified_results.txt.Combined.txt
classified_results.txt.Combined.txt_ALU_to_be_further_confirmed2.txt
classified_results.txt.Combined.txt_HERV-K_to_be_further_confirmed2.txt
classified_results.txt.Combined.txt_LINE1_to_be_further_confirmed2.txt
classified_results.txt.Combined.txt_NC_012920.1_to_be_further_confirmed2.txt
classified_results.txt.Combined.txt_SVA_to_be_further_confirmed2.txt
classified_results.txt.HERV.txt
classified_results.txt.LINE1.txt
classified_results.txt.LINE1.txt_non_transduction_only_middle_sgmt.txt
classified_results.txt.LINE1.txt_non_transduction.txt
classified_results.txt.LINE1.txt.tmp
classified_results.txt.LINE1.txt_to_be_decided_cases.txt
classified_results.txt.LINE1.txt_transductions.txt
classified_results.txt.merged_ALU.txt
classified_results.txt.merged_HERV.txt
classified_results.txt.merged_LINE1.txt
classified_results.txt.merged_SVA.txt
classified_results.txt.polyA.txt
classified_results.txt.SVA.txt
classified_results.txt.SVA.txt_non_transduction.txt
classified_results.txt.SVA.txt_non_transduction_within_rep_copy.txt
classified_results.txt.SVA.txt_to_be_decided_cases_no_ref_copy.txt
classified_results.txt.SVA.txt_to_be_decided_cases.txt
classified_results.txt.SVA.txt_transductions.txt
cns_2_contig.sorted.bam
cns_2_contig.sorted.bam.bai
ghost_reads.fa
ghost_reads.fa.assembled_final_out.fa
ghost_reads.fa.flanking.fa
ghost_reads.fa.masked.fa
ghost_reads.fa.separate_flanking.fa
ghost_reads.fa.separate_flanking.fa.algn_2_itself.sorted.bam
ghost_rep_copies.fa
ghost_rep_copy_flanks.fa
ghost_rep_copy_flanks.fa.algn_2_ref.sorted.bam
ghost_rep_copy_flanks.fa.algn_2_ref.sorted.bam.bai
pub_clip
run_xTEA_pipeline.sh
sample_id.txt
tmp
xtea.config
```

**Comment by simoncchu** [comment]
You are right. No joint calling for long reads. 
Also, the sensitivity maybe lower than expected for low coverage data. Most of the sites are detected but may be failed at the assembly step, thus are not reported in the final output which requires fully assembled sequence.
