### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by xuxif** [parklab/xTea#23]
Traceback (most recent call last):
  File "/root/xTea/xtea/x_TEA_main.py", line 1031, in <module>
    pkl_model = gc.load_model_from_file(sf_model)
  File "/root/xTea/xtea/x_genotype_classify.py", line 182, in load_model_from_file
    pickle_model = pickle.load(file, encoding='latin1')
ModuleNotFoundError: No module named 'sklearn.ensemble.forest'
Running command: sort -k1,1V -k2,2n -o ./xtea/HG002/Alu/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted ./xtea/HG002/Alu/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt

sort: cannot read: ./xtea/HG002/Alu/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt: No such file or directory
Traceback (most recent call last):
  File "/root/xTea/xtea/x_TEA_main.py", line 1065, in <module>
    gvcf.cvt_raw_rslt_to_gvcf(s_sample_id, sf_bam, sf_raw_rslt, i_rep_type, sf_ref, sf_vcf)
  File "/root/xTea/xtea/x_gvcf.py", line 199, in cvt_raw_rslt_to_gvcf
    with open(sf_raw_rslt_sorted) as fin_rslt:
FileNotFoundError: [Errno 2] No such file or directory: './xtea/HG002/Alu/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted'

**Comment by simoncchu** [comment]
https://github.com/parklab/xTea/issues/5
