### ISSUE TITLE
ValueError: file does not contain alignment data

### ISSUE THREAD

**Issue by dr-ashu-geno** [parklab/xTea#30]
Hello.

Thank you for developing xTea. 

I made shell scripts using the following command:
xTea/bin/xtea -i B-ID-list-for-xtea.txt -b A-CRAM-list-for-xtea.txt -x null -p xtea_results/ -o C-shell-script-for-running-xtea.sh -l /path/to/xTea/rep_lib_annotation/ -r /path/to/Homo_sapiens_assembly38.fasta -g /path/to/xTea/gencode.v33.annotation.gff3 --xtea /path/to/data/xTea/xTea/xtea/ -f 5907 -y 15 --slurm -q nc -n 8 -m 8

My input file is CRAM.
I have an error that is happening every time I run the program.
**This is the log:**

Working on "clip" step!
Ave coverage is 31.544: automatic parameters (clip, disc, clip-disc) with value (3, 4 ,1)

Clip cutoff: 3, 3, 1 are used!!!
Input bam /home/data/results/GM000036/GM000036.cram is sequenced from illumina platform!
Collected clipped reads file xtea_results/GM000036/pub_clip/0/GM000036.cram.clipped.fq doesn't exist. Generate it now!
Initial minimum clip cutoff is 2
('Output info: Collect clipped parts for file ', '/home/data/results/GM000036/GM000036.cram')

**And this is the error message when it crashes:**

[M::bwa_idx_load_from_disk] read 0 ALT contigs
[E::main_mem] fail to open file `xtea_results/GM000036/pub_clip/0/GM000036.cram.clipped.fq'.
Traceback (most recent call last):
  File "/home/ncbn-pg/users/saeidehashouri-pg/data/xTea/xTea/xtea/x_TEA_main.py", line 523, in <module>
    tem_locator.call_TEI_candidate_sites_from_multiple_alignmts(sf_annotation, sf_rep_cns, sf_rep, b_se,
  File "/lustre8/home/ncbn-pg/users/saeidehashouri-pg/data/xTea/xTea/xtea/x_TEI_locator.py", line 107, in call_TEI_candidate_sites_from_multiple_alignmts
    caller.call_TEI_candidate_sites_from_clip_reads_v2(sf_annotation, sf_rep_cns, sf_ref, b_se,
  File "/lustre8/home/ncbn-pg/users/saeidehashouri-pg/data/xTea/xTea/xtea/x_TEI_locator.py", line 633, in call_TEI_candidate_sites_from_clip_reads_v2
    bwa_align.two_stage_realign(sf_rep_cns, sf_ref, sf_all_clip_fq, sf_algnmt)
  File "/lustre8/home/ncbn-pg/users/saeidehashouri-pg/data/xTea/xTea/xtea/bwa_align.py", line 263, in two_stage_realign
    self.get_fully_mapped_algnmts(sf_sam_cns, sf_ref_cns, max_clip_len, sf_fully_sam, sf_unmap_fa, sf_polyA_fa)
  File "/lustre8/home/ncbn-pg/users/saeidehashouri-pg/data/xTea/xTea/xtea/bwa_align.py", line 167, in get_fully_mapped_algnmts
    bamfile = pysam.AlignmentFile(sf_sam, "r", reference_filename=sf_reference)  #
  File "pysam/libcalignmentfile.pyx", line 751, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 956, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file does not contain alignment data

Any help?

Please let me know if more information is needed.

Best regards,

**Comment by simoncchu** [comment]
could you change `-p xtea_results/` to the full path and try again?

**Comment by dr-ashu-geno** [comment]
Dear @simoncchu 

Thank you so much for your quick reply.

I put full path for all options in my command and it worked. 
As I had out of memory error too, I changed -m 8 to #SBATCH --mem=MaxMemPerCPU and it solved the problem. 

Thanks again,
Best,
