### ISSUE TITLE
No output for HERV

### ISSUE THREAD

**Issue by ramonamerong** [parklab/xTea#40]
When running xtea with a case/control:
```
$xteaPath/bin/xtea --case_control --tumor -i $output/sample_id.txt -b $output/case_ctrl_bam_list.txt -x null -p $output -o /hpc/pmc_gen/rvanamerongen/scripts/xtea_run_tumor_all.sh -l $xteaPath/data/rep_lib_annotation -r $hg38Path -g $xteaPath/data/known_genes_hg38.gff3 --xtea $xteaPath/xtea -f 5907 -y 15 --slurm -t 0-48:00 -n 16 -m 200
```
 I am not getting any output for HERV and it shows the following errors:
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/pmc_research/rvanamerongen/.conda/envs/xtea/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/pmc_research/rvanamerongen/.conda/envs/xtea/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_mutation.py", line 16, in unwrap_self_algn_read
    return XMutation.align_reads_to_cns_one_site(*arg, **kwarg)
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_mutation.py", line 104, in align_reads_to_cns_one_site
    self.select_qualified_alignments(ssam_hap1_tmp, sf_cns, ssam_hap1_slct)
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_mutation.py", line 165, in select_qualified_alignments
    bam_in = pysam.AlignmentFile(sf_algnmt, "rb", reference_filename=sf_ref)
  File "pysam/libcalignmentfile.pyx", line 741, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 990, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_TEA_main.py", line 1118, in <module>
    xmutation.call_mutations_from_reads_algnmt(sf_sites, sf_cns, n_len_cutoff, n_jobs, sf_merged_vcf)
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_mutation.py", line 46, in call_mutations_from_reads_algnmt
    self.align_reads_to_cns_in_parallel(l_records, n_jobs)
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_mutation.py", line 53, in align_reads_to_cns_in_parallel
    pool.map(unwrap_self_algn_read, list(zip([self] * len(l_records), l_records)), 1)
  File "/home/pmc_research/rvanamerongen/.conda/envs/xtea/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/pmc_research/rvanamerongen/.conda/envs/xtea/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False
Ave coverage is 42.336: automatic parameters (clip, disc, clip-disc) with value (3, 5 ,1)

clip,disc,polyA-cutoff is (3, 5, 1)
Traceback (most recent call last):
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_TEA_main.py", line 888, in <module>
    n_polyA_cutoff, sf_rep_cns, sf_flank, i_flk_len, bin_size, sf_output, b_tumor)
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_somatic_calling.py", line 93, in call_somatic_TE_insertion
    xclip_disc.sprt_TEI_to_td_orphan_non_td(sf_case_candidates, sf_non_td, sf_td, sf_td_sibling, sf_orphan)
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_clip_disc_filter.py", line 823, in sprt_TEI_to_td_orphan_non_td
    with open(sf_cns) as fin_cns:
FileNotFoundError: [Errno 2] No such file or directory: '/hpc/pmc_gen/rvanamerongen/output/xtea/tumor/PMCID205AAA/HERV/candidate_disc_filtered_cns_post_filtering.txt'
Traceback (most recent call last):
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_TEA_main.py", line 895, in <module>
    ccm.parse_high_confident_somatic(sf_candidate_list, sf_raw_somatic, sf_output)
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_somatic_calling.py", line 502, in parse_high_confident_somatic
    with open(sf_raw_somatic) as fin_somatic:
FileNotFoundError: [Errno 2] No such file or directory: '/hpc/pmc_gen/rvanamerongen/output/xtea/tumor/PMCID205AAA/HERV/candidate_disc_filtered_cns_post_filtering_somatic.txt'
Traceback (most recent call last):
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_TEA_main.py", line 1089, in <module>
    sf_sites=x_igv.gnrt_sites_single_sample(sf_sites, sf_bam_list)
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_igv.py", line 52, in gnrt_sites_single_sample
    with open(sf_sites) as fin_sites, open(sf_new_sites,"w") as fout_new:
FileNotFoundError: [Errno 2] No such file or directory: '/hpc/pmc_gen/rvanamerongen/output/xtea/tumor/PMCID205AAA/HERV/candidate_disc_filtered_cns2.txt'
Traceback (most recent call last):
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_TEA_main.py", line 1089, in <module>
    sf_sites=x_igv.gnrt_sites_single_sample(sf_sites, sf_bam_list)
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_igv.py", line 52, in gnrt_sites_single_sample
    with open(sf_sites) as fin_sites, open(sf_new_sites,"w") as fout_new:
FileNotFoundError: [Errno 2] No such file or directory: '/hpc/pmc_gen/rvanamerongen/output/xtea/tumor/PMCID205AAA/HERV/candidate_disc_filtered_cns_high_confident_post_filtering_somatic.txt'
Usage: x_TEA_main.py [options]

x_TEA_main.py: error: no such option: --bamsnap
Usage: x_TEA_main.py [options]

x_TEA_main.py: error: no such option: --bamsnap
Traceback (most recent call last):
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_TEA_main.py", line 1130, in <module>
    gff.annotate_results(sf_input, sf_output)
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_gene_annotation.py", line 238, in annotate_results
    with open(sf_ori_rslt) as fin_rslt, open(sf_out, "w") as fout_rslt:
FileNotFoundError: [Errno 2] No such file or directory: '/hpc/pmc_gen/rvanamerongen/output/xtea/tumor/PMCID205AAA/HERV/candidate_disc_filtered_cns_high_confident_post_filtering_somatic.txt'
/home/pmc_research/rvanamerongen/.conda/envs/xtea/lib/python3.6/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.18.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/pmc_research/rvanamerongen/.conda/envs/xtea/lib/python3.6/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.18.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_TEA_main.py", line 1033, in <module>
    gc.predict_for_site(pkl_model, sf_xTEA, sf_new)
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_genotype_classify.py", line 149, in predict_for_site
    site_features = self.prepare_arff_from_xTEA_output(sf_xTEA, sf_arff)
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_genotype_classify.py", line 130, in prepare_arff_from_xTEA_output
    l_features = self.load_in_feature_from_xTEA_output(sf_xTEA, b_train)
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_genotype_classify.py", line 192, in load_in_feature_from_xTEA_output
    with open(sf_xtea) as fin_xtea:
FileNotFoundError: [Errno 2] No such file or directory: '/hpc/pmc_gen/rvanamerongen/output/xtea/tumor/PMCID205AAA/HERV/candidate_disc_filtered_cns.txt.high_confident.post_filtering_somatic_with_gene.txt'
sort: cannot read: /hpc/pmc_gen/rvanamerongen/output/xtea/tumor/PMCID205AAA/HERV/candidate_disc_filtered_cns.txt.high_confident.post_filtering_somatic_with_gene_gntp.txt: No such file or directory
Running command: sort -k1,1V -k2,2n -o /hpc/pmc_gen/rvanamerongen/output/xtea/tumor/PMCID205AAA/HERV/candidate_disc_filtered_cns.txt.high_confident.post_filtering_somatic_with_gene_gntp.txt.sorted /hpc/pmc_gen/rvanamerongen/output/xtea/tumor/PMCID205AAA/HERV/candidate_disc_filtered_cns.txt.high_confident.post_filtering_somatic_with_gene_gntp.txt

Traceback (most recent call last):
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_TEA_main.py", line 1065, in <module>
    gvcf.cvt_raw_rslt_to_gvcf(s_sample_id, sf_bam, sf_raw_rslt, i_rep_type, sf_ref, sf_vcf)
  File "/hpc/pmc_gen/rvanamerongen/software/callers/xtea/xtea/x_gvcf.py", line 199, in cvt_raw_rslt_to_gvcf
    with open(sf_raw_rslt_sorted) as fin_rslt:
FileNotFoundError: [Errno 2] No such file or directory: '/hpc/pmc_gen/rvanamerongen/output/xtea/tumor/PMCID205AAA/HERV/candidate_disc_filtered_cns.txt.high_confident.post_filtering_somatic_with_gene_gntp.txt.sorted'

```
The `x_TEA_main.py: error: no such option: --bamsnap`, however, is also present in the output for the other transposon types but they did have a vcf file.

**Comment by simoncchu** [comment]
Does it work well for other types of repeats? For example, on L1. I haven't seen any somatic HERV reported before, although the module should work.

**Comment by ramonamerong** [comment]
Yes, the other types are all reported. I looked at the bam file that was likely the culprit and it seems that all bam files inside HERV/tmp/mutations only consist of a header "@HD	VN:1.6	SO:coordinate".
Should I just ignore the '--bamsnap' error?

**Comment by simoncchu** [comment]
yeah, you can just ignore these errors.
