### ISSUE TITLE
Error in SVA calling(ValueError: file does not contain alignment data)

### ISSUE THREAD

**Issue by nhkong** [parklab/xTea#48]
Hi, 
Thank you for making this useful pipeline! While I was running xTEA from short reads, somehow I couldn't produce VCF file for SVA although I successfully get output vcf for L1 and Alu. The first error generated was "ValueError: file does not contain alignment data" which wasn't in other TE running. Do you have any idea to solve this problem? This is the stdout:

```

k.nahyun@compute1-exec-136:~$ sh /storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/SVA/run_xTEA_pipeline.sh
Working on "clip" step!
Ave coverage is 49.706: automatic parameters (clip, disc, clip-disc) with value (4, 7 ,1)

Clip cutoff: 4, 4, 1 are used!!!
Input bam /storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/data/UDN963226-1682-8d92b331-2f92-472c-bb16-dd79a2ed7767.bam is sequenced from illumina platform!
Collected clipped reads file /storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/pub_clip/0/UDN963226-1682-8d92b331-2f92-472c-bb16-dd79a2ed7767.bam.clipped.fq already exist!
('Output info: Re-align clipped parts for file ', '/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/data/UDN963226-1682-8d92b331-2f92-472c-bb16-dd79a2ed7767.bam')
Running command: bwa mem -t 15 -T 9 -k 9 -o /storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/SVA/tmp/UDN963226-1682-8d92b331-2f92-472c-bb16-dd79a2ed7767.bam.clipped.sam_cns.sam /storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/rep_lib_annotation/consensus/SVA.fa /storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/pub_clip/0/UDN963226-1682-8d92b331-2f92-472c-bb16-dd79a2ed7767.bam.clipped.fq

[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 3601324 sequences (150000045 bp)...
[M::process] read 2969640 sequences (126020436 bp)...
Killed
Traceback (most recent call last):
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_TEA_main.py", line 422, in <module>
    wfolder_pub_clip, b_force, max_cov_cutoff, sf_out)
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_TEI_locator.py", line 109, in call_TEI_candidate_sites_from_multiple_alignmts
    sf_new_pub, i_idx_bam, b_force, max_cov, sf_out_tmp)
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_TEI_locator.py", line 633, in call_TEI_candidate_sites_from_clip_reads_v2
    bwa_align.two_stage_realign(sf_rep_cns, sf_ref, sf_all_clip_fq, sf_algnmt)
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/bwa_align.py", line 263, in two_stage_realign
    self.get_fully_mapped_algnmts(sf_sam_cns, sf_ref_cns, max_clip_len, sf_fully_sam, sf_unmap_fa, sf_polyA_fa)
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/bwa_align.py", line 167, in get_fully_mapped_algnmts
    bamfile = pysam.AlignmentFile(sf_sam, "r", reference_filename=sf_reference)  #
  File "pysam/libcalignmentfile.pyx", line 751, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 956, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file does not contain alignment data
Working on "disc" step!
Traceback (most recent call last):
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_TEA_main.py", line 439, in <module>
    m_original_sites = xfilter.load_in_candidate_list(sf_candidate_list)
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_intermediate_sites.py", line 149, in load_in_candidate_list
    with open(sf_candidate_list) as fin_candidate_sites:
FileNotFoundError: [Errno 2] No such file or directory: '/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/SVA/candidate_list_from_clip.txt'
Working on "clip-disc-filtering" step!
Current working folder is: /storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/SVA/tmp/cns/

Ave coverage is 49.982: automatic parameters (clip, disc, clip-disc) with value (4, 7 ,1)

Mean insert size is: 456.79731168186396

Standard derivation is: 176.74872197608607

Read length is: 151.0

Maximum insert size is: 987

Average coverage is: 49.982

Filter (on cns) cutoff: 4 and 7 are used!!!
Traceback (most recent call last):
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_TEA_main.py", line 534, in <module>
    n_clip_cutoff, n_disc_cutoff, sf_output)
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_clip_disc_filter.py", line 1540, in call_MEIs_consensus
    sf_disc_fa, sf_raw_disc)
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_clip_disc_filter.py", line 3324, in collect_clipped_disc_reads
    sf_disc_fa_tmp)
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_clip_disc_filter.py", line 296, in collect_clipped_disc_reads_of_given_list
    with open(sf_candidate_list) as fin_list:
FileNotFoundError: [Errno 2] No such file or directory: '/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/SVA/candidate_list_from_disc.txt'
Current working folder is: /storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/SVA/tmp/transduction/

Ave coverage is 49.870000000000005: automatic parameters (clip, disc, clip-disc) with value (4, 7 ,1)

Mean insert size is: 456.0272645946843

Standard derivation is: 176.628666089216

Traceback (most recent call last):
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_TEA_main.py", line 594, in <module>
    i_rep_type, b_tumor, sf_tmp_slct)
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_transduction.py", line 54, in re_slct_with_clip_raw_disc_sites
    m_te_candidates=xintmdt.load_in_candidate_list_str_version(sf_candidates) #TE candidates
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_intermediate_sites.py", line 184, in load_in_candidate_list_str_version
    with open(sf_candidate_list) as fin_candidate_sites:
FileNotFoundError: [Errno 2] No such file or directory: '/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/SVA/candidate_disc_filtered_cns.txt'
Current working folder is: /storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/SVA/tmp/transduction/

Traceback (most recent call last):
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_TEA_main.py", line 897, in <module>
    sf_new_out, b_tumor)
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_post_filter.py", line 416, in run_post_filtering
    l_old_rcd=xtea_parser.load_in_xTEA_rslt(sf_xtea_rslt)
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_post_filter.py", line 495, in load_in_xTEA_rslt
    with open(sf_rslt) as fin_in:
FileNotFoundError: [Errno 2] No such file or directory: '/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/SVA/candidate_disc_filtered_cns2.txt'
Traceback (most recent call last):
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_TEA_main.py", line 897, in <module>
    sf_new_out, b_tumor)
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_post_filter.py", line 416, in run_post_filtering
    l_old_rcd=xtea_parser.load_in_xTEA_rslt(sf_xtea_rslt)
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_post_filter.py", line 495, in load_in_xTEA_rslt
    with open(sf_rslt) as fin_in:
FileNotFoundError: [Errno 2] No such file or directory: '/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/SVA/candidate_disc_filtered_cns2.txt.high_confident'
Traceback (most recent call last):
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_TEA_main.py", line 1033, in <module>
    gff.annotate_results(sf_input, sf_output)
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_gene_annotation.py", line 238, in annotate_results
    with open(sf_ori_rslt) as fin_rslt, open(sf_out, "w") as fout_rslt:
FileNotFoundError: [Errno 2] No such file or directory: '/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering.txt'
/usr/local/lib/python3.6/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.0.1 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_TEA_main.py", line 932, in <module>
    gc.predict_for_site(sf_model, sf_xTEA, sf_new)
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_genotype_classify.py", line 146, in predict_for_site
    with open(sf_xTEA) as fin_xTEA, open(sf_new, "w") as fout_new:
FileNotFoundError: [Errno 2] No such file or directory: '/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene.txt'
Running command: sort -k1,1V -k2,2n -o /storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted /storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt

sort: cannot read: /storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt: No such file or directory
Traceback (most recent call last):
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_TEA_main.py", line 964, in <module>
    gvcf.cvt_raw_rslt_to_gvcf(s_sample_id, sf_bam, sf_raw_rslt, i_rep_type, sf_ref, sf_vcf)
  File "/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/xtea/x_gvcf.py", line 199, in cvt_raw_rslt_to_gvcf
    with open(sf_raw_rslt_sorted) as fin_rslt:
FileNotFoundError: [Errno 2] No such file or directory: '/storage1/fs1/jin810/Active/Nahyun/THESIS_PROJECT/TE/xTEA/JOBS/20220531_CP_trio/UDN963226P/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted'
Usage: x_TEA_main.py [options]

x_TEA_main.py: error: no such option: --bamsnap
Usage: x_TEA_main.py [options]

x_TEA_main.py: error: no such option: --bamsnap

```

**Comment by simoncchu** [comment]
Try with a larger memory for SVA.

**Comment by nhkong** [comment]
That worked! Thank you so much!
