### ISSUE TITLE
ValueError: unknown field code 'AH' in record 'SQ'

### ISSUE THREAD

**Issue by Wonsinsin** [parklab/xTea#49]
Hi,
I am facing a problem in running 'sh run_xTEA_pipeline.sh '.

 I am getting the following error:

Working on "clip" step!
Traceback (most recent call last):
  File "/home2/wangyx/miniconda3/envs/xtea/lib/x_TEA_main.py", line 505, in <module>
    b_force, b_tumor, f_purity)
  File "/home2/wangyx/miniconda3/envs/xtea/lib/x_TEA_main.py", line 364, in automatic_gnrt_parameters
    rcd=x_basic_info.get_cov_is_rlth(sf_bam_list, sf_ref, search_win, b_force)
  File "/home2/wangyx/miniconda3/envs/xtea/lib/x_basic_info.py", line 47, in get_cov_is_rlth
    m_info=self.collect_dump_basic_info_samples(sf_bam_list, sf_ref, search_win)
  File "/home2/wangyx/miniconda3/envs/xtea/lib/x_basic_info.py", line 60, in collect_dump_basic_info_samples
    m_sample_info=self.collect_basic_info_samples(sf_bam_list, sf_ref, search_win)
  File "/home2/wangyx/miniconda3/envs/xtea/lib/x_basic_info.py", line 117, in collect_basic_info_samples
    l_sites=self._random_slct_site(sf_bam, sf_ref, n_sites)
  File "/home2/wangyx/miniconda3/envs/xtea/lib/x_basic_info.py", line 428, in _random_slct_site
    m_chrm_info=bam_info.get_all_chrom_name_length()
  File "/home2/wangyx/miniconda3/envs/xtea/lib/x_alignments.py", line 56, in get_all_chrom_name_length
    header = bamfile.header
  File "pysam/calignmentfile.pyx", line 1258, in pysam.calignmentfile.AlignmentFile.header.__get__ (pysam/calignmentfile.c:15426)
ValueError: unknown field code 'AH' in record 'SQ'

The input file 'sample.Mdup.recal.bam' is processed by gatk. Can you help me? Thank you so much!

**Comment by simoncchu** [comment]
Looks like a bam file issue. Probably there are "AH" and "SQ" code in reads, but no in the bam header. You should check that. Inside, xTea is using pysam to parse the bam files, and pysam is a wrapper for the samtools libraries (htslib). I think if you run with samtools or similar tools, you may have the similar issue. You should check the bam file first.

**Comment by Wonsinsin** [comment]
> Looks like a bam file issue. Probably there are "AH" and "SQ" code in reads, but no in the bam header. You should check that. Inside, xTea is using pysam to parse the bam files, and pysam is a wrapper for the samtools libraries (htslib). I think if you run with samtools or similar tools, you may have the similar issue. You should check the bam file first.

Thank you for your reply！I check my bam files. As the picture shows, there are "AH" and "SQ" code in the bam header. And I am sure it's normal to run samtools. I don't know why this happens.

Another question. Does it affect the final result, if I remain the primary assembly chromosome and remove small segments, just labeled by "AH"?

Thank you so much!!
![image](https://user-images.githubusercontent.com/107989454/175246809-4f406c1d-415e-42f6-a9ff-03b007a80f95.png)
![image](https://user-images.githubusercontent.com/107989454/175246952-55ad8c13-10a4-4d52-be8d-2ca5c35b78b8.png)

**Comment by simoncchu** [comment]
@Wonsinsin there shouldn't be a AH field in the SQ filed. You can just replace the header part by removing the AH field and try again. It doesn't affect the final results.
