### ISSUE TITLE
clipped.fq not found

### ISSUE THREAD

**Issue by ohan-Bioinfo** [parklab/xTea#64]
Developer any idea what's going on here

Looking for files and cant be found should i prepare these files

In fact i just extracted the rep_annotation after wget, do i have preprocess the file, seems all files are indexed and ready? 

```
('Output info: Re-align clipped parts for file ', '/usr/local/bin/LocalData/bamFile/NA12878.sort.bam')
Running command: bwa mem -t 1 -T 9 -k 9 -o ./NA12878/L1/tmp/NA12878.sort.bam.clipped.sam_cns.sam LocalData/RepeatLib/consensus/LINE1.fa ./NA12878/pub_clip/0/NA12878.sort.bam.clipped.fq

[M::bwa_idx_load_from_disk] read 0 ALT contigs
[E::main_mem] fail to open file `./NA12878/pub_clip/0/NA12878.sort.bam.clipped.fq'.
Traceback (most recent call last):
  File "./x_TEA_main.py", line 419, in <module>
    tem_locator.call_TEI_candidate_sites_from_multiple_alignmts(sf_annotation, sf_rep_cns, sf_rep, b_se,
  File "/usr/local/bin/x_TEI_locator.py", line 107, in call_TEI_candidate_sites_from_multiple_alignmts
    caller.call_TEI_candidate_sites_from_clip_reads_v2(sf_annotation, sf_rep_cns, sf_ref, b_se,
  File "/usr/local/bin/x_TEI_locator.py", line 633, in call_TEI_candidate_sites_from_clip_reads_v2
    bwa_align.two_stage_realign(sf_rep_cns, sf_ref, sf_all_clip_fq, sf_algnmt)
  File "/usr/local/bin/bwa_align.py", line 263, in two_stage_realign
    self.get_fully_mapped_algnmts(sf_sam_cns, sf_ref_cns, max_clip_len, sf_fully_sam, sf_unmap_fa, sf_polyA_fa)
  File "/usr/local/bin/bwa_align.py", line 167, in get_fully_mapped_algnmts
    bamfile = pysam.AlignmentFile(sf_sam, "r", reference_filename=sf_reference)  #
  File "pysam/libcalignmentfile.pyx", line 751, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 956, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file does not contain alignment data
Working on "clip-disc-filtering" step!
Current working folder is: ./NA12878/L1/tmp/cns/

Ave coverage is 0: automatic parameters (clip, disc, clip-disc) with value (1, 3 ,0)

Mean insert size is: 0.0

Standard derivation is: 0.0

Read length is: 0.0

Maximum insert size is: 0

Average coverage is: 0

Filter (on cns) cutoff: 1 and 3 are used!!!
Traceback (most recent call last):
  File "./x_TEA_main.py", line 532, in <module>
    x_cd_filter.call_MEIs_consensus(sf_candidate_list, sf_raw_disc, iextnd, bin_size, sf_cns, sf_flank,
  File "/usr/local/bin/x_clip_disc_filter.py", line 1539, in call_MEIs_consensus
    m_lowq_clip_cnt = self.collect_clipped_disc_reads(sf_candidate_list, extnd, bin_size, sf_clip_fq,
  File "/usr/local/bin/x_clip_disc_filter.py", line 3322, in collect_clipped_disc_reads
    l_low_mapq_clip=xclip_disc.collect_clipped_disc_reads_of_given_list(sf_candidate_list, extnd,
  File "/usr/local/bin/x_clip_disc_filter.py", line 296, in collect_clipped_disc_reads_of_given_list
    with open(sf_candidate_list) as fin_list:
FileNotFoundError: [Errno 2] No such file or directory: './NA12878/L1/candidate_list_from_disc.txt'
Current working folder is: ./NA12878/L1/tmp/transduction/

Ave coverage is 0: automatic parameters (clip, disc, clip-disc) with value (1, 3 ,0)

```

**Comment by simoncchu** [comment]
Try to use the full path of the working folder, instead of `./NA12878`?
