### ISSUE TITLE
--lc: invalid integer value: 

### ISSUE THREAD

**Issue by ohan-Bioinfo** [parklab/xTea#70]
i'm using this command 
```
python /cromwell_root/bin/gnrt_pipeline_local_v38.pyc -D -i ${sample} \
            -b ${input_bam} \
            -x null \
            --xtea /cromwell_root/bin/ -p /cromwell_root/ -o submit.sh \
            -l ${repeats_tar} \
            -r ${genome_tar} \
            -g ${Annotation} \
            -y 1 -f 1 -n 4 
```

```
Obtained script
#!/bin/bash

#SBATCH -n 4
#SBATCH -t None
#SBATCH --mem=NoneG
#SBATCH -p None
#SBATCH -o NDX-22-829-004_%j.out
#SBATCH --mail-type=END
#SBATCH --mail-user=chong.simonchu@gmail.com
PREFIX=/cromwell_root/NDX-22-829-004/L1/
############
############
ANNOTATION=/cromwell_root/rep_lib_annotation/LINE/hg38/hg38_L1_larger_500_with_all_L1HS.out
REF=/cromwell_root/genome.fa
GENE=/cromwell_root/fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/gencode.v33.annotation.gff3.gz
L1_COPY_WITH_FLANK=/cromwell_root/rep_lib_annotation/LINE/hg38/hg38_L1HS_copies_larger_5K_with_flank.fa
SF_FLANK=/cromwell_root/rep_lib_annotation/LINE/hg38/hg38_FL_L1_flanks_3k.fa
L1_CNS=/cromwell_root/rep_lib_annotation/consensus/LINE1.fa
XTEA_PATH=/cromwell_root/bin/
BAM_LIST=${PREFIX}"bam_list.txt"
BAM1=${PREFIX}"10X_phased_possorted_bam.bam"
BARCODE_BAM=${PREFIX}"10X_barcode_indexed.sorted.bam"
TMP=${PREFIX}"tmp/"
TMP_CLIP=${PREFIX}"tmp/clip/"
TMP_CNS=${PREFIX}"tmp/cns/"
############
############
python ${XTEA_PATH}"x_TEA_main.pyc" -C -i ${BAM_LIST} --lc None --rc None --cr None -r ${L1_COPY_WITH_FLANK} -a ${ANNOTATION} --cns ${L1_CNS} --ref ${REF} -p ${TMP} -o ${PREFIX}"candidate_list_from_clip.txt" -n 4 --cp /cromwell_root/NDX-22-829-004/pub_clip/
```

Error

```
Usage: x_TEA_main.pyc [options]

x_TEA_main.pyc: error: option --lc: invalid integer value: 'None'

```
Note no flag is giving in the gnrt_pipeline_local_v38.pyc script

**Comment by simoncchu** [comment]
why do you use `gnrt_pipeline_local_v38.pyc` ?

**Comment by ohan-Bioinfo** [comment]
Because i'm using cloud platform, FireTerra

**Comment by ohan-Bioinfo** [comment]
```
workflow Xtea {
    call Transposable_Element
}   


task Transposable_Element {
    File input_bam
    File genome_tar
    File repeats_tar
    File Annotation
    File sample
    
    
        command {
        
        	ln -s /usr/local/bin/ /cromwell_root/ 
         
          
            
            
            
        	python /cromwell_root/bin/gnrt_pipeline_local_v38.pyc -D -i ${sample} \
            -b ${input_bam} \
            -x null --xtea /cromwell_root/bin/ -p /cromwell_root/ -o /cromwell_root/submit.sh \
            -l /cromwell_root/${repeats_tar} \
            -r ${genome_tar} \
            -g ${Annotation} \
            -y 1 -f 1 -n 4        
           


            sed 's/sbatch/sh/g' submit.sh > submit1.sh
            cat submit1.sh
            
            
            chmod +x submit.sh
            sh submit1.sh
            
        }
        
        runtime {
    	    cpu: 4
  	    	memory: "24GB"
            disks: "local-disk 501 HDD"
            docker: "warbler/xteab:v10"
        }        
        output {
        	File results= "${sample}.Transposable_Element.results"
        }

}
```

**Comment by ohan-Bioinfo** [comment]
Some file cant be found, any suggestion? 

```
Working on "clip" step!
Ave coverage is 0: automatic parameters (clip, disc, clip-disc) with value (1, 3 ,0)

Clip cutoff: 1, 1, 0 are used!!!
[E::hts_open_format] Failed to open file "" : No such file or directory
Traceback (most recent call last):
File "/cromwell_root/bin/x_TEA_main.py", line 419, in <module>
tem_locator.call_TEI_candidate_sites_from_multiple_alignmts(sf_annotation, sf_rep_cns, sf_rep, b_se,
File "/usr/local/bin/x_TEI_locator.py", line 114, in call_TEI_candidate_sites_from_multiple_alignmts
b_with_chr = bam_info.is_chrm_contain_chr()
File "/usr/local/bin/x_alignments.py", line 77, in is_chrm_contain_chr
samfile = pysam.AlignmentFile(self.sf_bam, "rb", reference_filename=self.sf_reference)
File "pysam/libcalignmentfile.pyx", line 751, in pysam.libcalignmentfile.AlignmentFile.__cinit__
File "pysam/libcalignmentfile.pyx", line 950, in pysam.libcalignmentfile.AlignmentFile._open
FileNotFoundError: [Errno 2] could not open alignment file ``: No such file or directory
```

**Comment by simoncchu** [comment]
please use this version https://github.com/parklab/xTea/issues/60

**Comment by ohan-Bioinfo** [comment]
What do he need and cant be found

```
[E::hts_open_format] Failed to open file "" : No such file or directory
Working on "clip" step!
Ave coverage is 0: automatic parameters (clip, disc, clip-disc) with value (1, 3 ,0)
```
