### ISSUE TITLE
Gene list Error

### ISSUE THREAD

**Issue by ohan-Bioinfo** [parklab/xTea#74]
I assume the script trying to reach the gene list , an error occur 
Would you please advice if familiar

```
Traceback (most recent call last):
  File "/cromwell_root/bin/x_TEA_main.py", line 1031, in <module>
    gff.load_gene_annotation_with_extnd(iextnd)
  File "/usr/local/bin/x_gene_annotation.py", line 71, in load_gene_annotation_with_extnd
    ori_start_pos=int(fields[3])
ValueError: invalid literal for int() with base 10: 'pseudogene'
/miniconda/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.0.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(
Traceback (most recent call last):
  File "/cromwell_root/bin/x_TEA_main.py", line 932, in <module>
    gc.predict_for_site(sf_model, sf_xTEA, sf_new)
  File "/usr/local/bin/x_genotype_classify.py", line 146, in predict_for_site
    with open(sf_xTEA) as fin_xTEA, open(sf_new, "w") as fout_new:
FileNotFoundError: [Errno 2] No such file or directory: '/cromwell_root/WorkingDir/NDX-22-829-004/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene.txt'
sort: cannot read: /cromwell_root/WorkingDir/NDX-22-829-004/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt: No such file or directory
Running command: sort -k1,1V -k2,2n -o /cromwell_root/WorkingDir/NDX-22-829-004/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted /cromwell_root/WorkingDir/NDX-22-829-004/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt

Traceback (most recent call last):
  File "/cromwell_root/bin/x_TEA_main.py", line 964, in <module>
    gvcf.cvt_raw_rslt_to_gvcf(s_sample_id, sf_bam, sf_raw_rslt, i_rep_type, sf_ref, sf_vcf)
  File "/usr/local/bin/x_gvcf.py", line 199, in cvt_raw_rslt_to_gvcf
    with open(sf_raw_rslt_sorted) as fin_rslt:
FileNotFoundError: [Errno 2] No such file or directory: '/cromwell_root/WorkingDir/NDX-22-829-004/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted'
Usage: x_TEA_main.py [options]

x_TEA_main.py: error: no such option: --bamsnap
Usage: x_TEA_main.py [options]

x_TEA_main.py: error: no such option: --bamsnap
```

should i reformat the gff file?

**Comment by simoncchu** [comment]
Which gene annotation file (gff file) do you use as input?

**Comment by ohan-Bioinfo** [comment]
i obtain the gff file from giving link https://www.gencodegenes.org/human/release_33lift37.html

**Comment by simoncchu** [comment]
The file should work. It's weird. Not sure exactly which step is wrong.

**Comment by simoncchu** [comment]
Could you post the top lines of your gff3 file? The error message seems clear "ValueError: invalid literal for int() with base 10: 'pseudogene'", the 3rd column is not a number but "pseudogene".

**Comment by ohan-Bioinfo** [comment]
```
##gff-version 3
#!gff-spec-version 1.21
#!processor NCBI annotwriter
#!genome-build GRCh38.p14
#!genome-build-accession NCBI_Assembly:GCF_000001405.40
#!annotation-source NCBI Homo sapiens Annotation Release 110
##sequence-region NC_000001.11 1 248956422
##species https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=9606
NC_000001.11    RefSeq  region  1       248956422       .       +       .       ID=NC_000001.11:1..248956422;Dbxref=taxon:9606;Name=1;chromosome=1;gbkey=Src;genome=chromosome;mol_type=genomic DNA
NC_000001.11    BestRefSeq      pseudogene      11874   14409   .       +       .       ID=gene-DDX11L1;Dbxref=GeneID:100287102,HGNC:HGNC:37102;Name=DDX11L1;description=DEAD/H-box helicase 11 like 1 (pseudogene);gbkey=Gene;gene=DDX11L1;gene_biotype=transcribed_pseudogene;pseudo=true
```

**Comment by simoncchu** [comment]
Could you try with `https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_33/gencode.v33.annotation.gff3.gz` ? (decompress)

**Comment by ohan-Bioinfo** [comment]
after using above gff:

what this means [`DISC-TD-STEP:] Filter out chr8:42182019, no enough disc support!`


```

[DISC-TD-STEP:] Filter out chr8:42182019, no enough disc support!
[DISC-TD-STEP:] Filter out chr1:108807576, no enough disc support!
[DISC-TD-STEP:] Filter out chr15:19988084, no enough disc support!
[DISC-TD-STEP:] Filter out chr15:19988312, no enough disc support!
Running command: bwa mem -t 8 -o /cromwell_root/WorkingDir/01-MD-20-02-001.hg38.aligned.duplicate_marked.sorted/L1/tmp/transduction/temp_transduction_disc_cns.sam /cromwell_root/fc-00bcc31d-9daf-40fa-bca6-2c6aa332a71c/rep_lib_annotation/consensus/LINE1.fa /cromwell_root/WorkingDir/01-MD-20-02-001.hg38.aligned.duplicate_marked.sorted/L1/tmp/transduction/raw_candidate_sites_all_disc_focal_sites.fa

Current working folder is: /cromwell_root/WorkingDir/01-MD-20-02-001.hg38.aligned.duplicate_marked.sorted/L1/tmp/transduction/

Ave coverage is 10.552000000000001: automatic parameters (clip, disc, clip-disc) with value (2, 3 ,0)

Mean insert size is: 177.52539486568182

Standard derivation is: 118.77350691544784

[re-select step]:Filtered out: chr1:165752252 fall in repetitive region.
[re-select step]:Filtered out: chr1:178747171 fall in repetitive region.
[re-select step]:Filtered out: chr1:178747358 fall in repetitive region.
[re-select step]:Filtered out: chr1:178747601 fall in repetitive region.
[re-select step]:Filtered out: chr2:12023938 fall in repetitive region.
[re-select step]:Filtered out: chr2:131480777 fall in repetitive region.
[re-select step]:Filtered out: chr2:148947924 fall in repetitive region.
[re-select step]:Filtered out: chr2:167714308 fall in repetitive region.
[re-select step]:Filtered out: chr2:167715162 fall in repetitive region.
[re-select step]:Filtered out: chr2:167715531 fall in repetitive region.
[re-select step]:Filtered out: chr3:39411118 fall in repetitive region.
[re-select step]:Filtered out: chr5:80351177 fall in repetitive region.
[re-select step]:Filtered out: chr5:80351398 fall in repetitive region.
[re-select step]:Filtered out: chr5:80351691 fall in repetitive region.
[re-select step]:Filtered out: chr5:100391625 fall in repetitive region.
[re-select step]:Filtered out: chr6:26897533 fall in repetitive region.
[re-select step]:Filtered out: chr6:26898384 fall in repetitive region.
[re-select step]:Filtered out: chr6:26899051 fall in repetitive region.
[re-select step]:Filtered out: chr6:32326239 fall in repetitive region.
[re-select step]:Filtered out: chr6:33451836 fall in repetitive region.
[re-select step]:Filtered out: chr8:12665235 fall in repetitive region.
[re-select step]:Filtered out: chr8:12665350 fall in repetitive region.
[re-select step]:Filtered out: chr8:100706886 fall in repetitive region.
[re-select step]:Filtered out: chr8:100706997 fall in repetitive region.
[re-select step]:Filtered out: chr9:82058876 fall in repetitive region.
[re-select step]:Filtered out: chr9:82059226 fall in repetitive region.
[re-select step]:Filtered out: chr9:82059833 fall in repetitive region.
[re-select step]:Filtered out: chr10:77982066 fall in repetitive region.
[re-select step]:Filtered out: chr11:6108638 fall in repetitive region.
[re-select step]:Filtered out: chr11:89047236 fall in repetitive region.
[re-select step]:Filtered out: chr11:89047796 fall in repetitive region.
[re-select step]:Filtered out: chr11:89753656 fall in repetitive region.
[re-select step]:Filtered out: chr11:108229378 fall in repetitive region.
[re-select step]:Filtered out: chr14:24183972 fall in repetitive region.
[re-select step]:Filtered out: chr15:92795885 fall in repetitive region.
[re-select step]:Filtered out: chr17:45436837 fall in repetitive region.
[re-select step]:Filtered out: chr17:45437350 fall in repetitive region.
[re-select step]:Filtered out: chr17:45437673 fall in repetitive region.
[re-select step]:Filtered out: chr17:48875109 fall in repetitive region.
[re-select step]:Filtered out: chr17:59056942 fall in repetitive region.
[re-select step]:Filtered out: chr17:59057075 fall in repetitive region.
[re-select step]:Filtered out: chrX:105406697 fall in repetitive region.
Blacklist file null does not exist!
/miniconda/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.0.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
warnings.warn(
[2023-01-23 20:52:45.644] Start to evalute the model:
[2023-01-23 20:52:45.644] Evaluating cascade layer = 0
Running command: sort -k1,1V -k2,2n -o /cromwell_root/WorkingDir/01-MD-20-02-001.hg38.aligned.duplicate_marked.sorted/L1/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted /cromwell_root/WorkingDir/01-MD-20-02-001.hg38.aligned.duplicate_marked.sorted/L1/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt
```

**Comment by ohan-Bioinfo** [comment]
the pipeline stop here without an error:

```
[re-select step]:Filtered out: chr17:59056942 fall in repetitive region.
[re-select step]:Filtered out: chr17:59057075 fall in repetitive region.
[re-select step]:Filtered out: chrX:105406697 fall in repetitive region.
Blacklist file null does not exist!
[2023-01-23 21:25:49.264] Start to evalute the model:
[2023-01-23 21:25:49.264] Evaluating cascade layer = 0 
Running command: sort -k1,1V -k2,2n -o /cromwell_root/WorkingDir/01-MD-20-02-001.hg38.aligned.duplicate_marked.sorted/L1/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted /cromwell_root/WorkingDir/01-MD-20-02-001.hg38.aligned.duplicate_marked.sorted/L1/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt
```
