### ISSUE TITLE
Issue running locally

### ISSUE THREAD

**Issue by RSWilson1** [parklab/xTea#81]
Hi I am testing this tool out for running on a lot of samples, however I am having trouble running it locally.
Do you have any documentation of running it locally and not on SLURM etc...?

I also hit this problem

```shell
(xtea_env) rswilson1:~/Documents/$ xtea_hg19 -i 1000G/HG01879/xTea/sample_id.txt -b 1000G/HG01879/HG01879.mapped.ILLUMINA.bwa.ACB.low_coverage.20120522.bam -r MELT_example_data/hs37d5.fa -p /
Traceback (most recent call last):
  File "/home/rswilson1/anaconda3/envs/xtea_env/bin/xtea_hg19", line 1130, in <module>
    if os.path.isfile(sf_bams_10X) == False:
  File "/home/rswilson1/anaconda3/envs/xtea_env/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
``` 

Any idea on what is causing this problem or advice for running xtea?

**Comment by simoncchu** [comment]
It should work well locally. Could you change the `-p` option to the full path, rather than "/", and try again?
