### ISSUE TITLE
no such option: --bamsnap 

### ISSUE THREAD

**Issue by hzlnutspread** [parklab/xTea#84]
When I run the tool locally after downloading all of the dependencies manually, I run all of the bash scripts but they all fail with the following error:

```
x_TEA_main.py: error: no such option: --bamsnap
Usage: x_TEA_main.py [options]
```

Should I remove this option from the command in the bash files or what should be done to overcome this error? 

Thanks

**Comment by simoncchu** [comment]
yes, please remove this option. It doesn't affect the results.

**Comment by hzlnutspread** [comment]
@simoncchu when I remove --bamsnap from the last two lines i still get an error:

```
Traceback (most recent call last):
  File "/powerplant/workspace/hrakws/xTea_test/xTea/xtea/x_TEA_main.py", line 599, in <module>
    xtransduction.call_candidate_transduction_v3(sf_tmp_slct, sf_candidate_list, x_cd_filter,
  File "/powerplant/workspace/hrakws/xTea_test/xTea/xtea/x_transduction.py", line 202, in call_candidate_transduction_v3
    bwa_align.realign_clipped_read_with_polyA(sf_flank_with_poly, sf_clip_fq, sf_clip_algnmt)
  File "/powerplant/workspace/hrakws/xTea_test/xTea/xtea/bwa_align.py", line 49, in realign_clipped_read_with_polyA
    with open(sf_sam1) as fin_sam1:
FileNotFoundError: [Errno 2] No such file or directory: '/powerplant/workspace/hrakws/xTea_test/xTea/outputs/GoldenDelicious/L1/tmp/transduction/temp_transduction_clip.sam.non_polyA.sam'
Current working folder is: /powerplant/workspace/hrakws/xTea_test/xTea/outputs/GoldenDelicious/L1/tmp/transduction/

Ave coverage is 64.88499999999999: automatic parameters (clip, disc, clip-disc) with value (5, 8 ,2)

Mean insert size is: 477.233675126293

Standard derivation is: 212.3771127849177

Blacklist file null does not exist!
/powerplant/workspace/hrakws/xTea_test/xTea/venv/lib/python3.9/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.0.1 when using version 1.2.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
[2023-06-09 22:45:35.820] Start to evalute the model:
[2023-06-09 22:45:35.820] Evaluating cascade layer = 0 
Running command: sort -k1,1V -k2,2n -o /powerplant/workspace/hrakws/xTea_test/xTea/outputs/GoldenDelicious/L1/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted /powerplant/workspace/hrakws/xTea_test/xTea/outputs/GoldenDelicious/L1/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt
```

Thoughts?

**Comment by simoncchu** [comment]
Could you post the content of the generated command file named like `run_xTEA_pipeline.sh` ?

**Comment by hzlnutspread** [comment]
Note I've removed the --bamsnap option from the bottom two commands
```
#!/bin/bash

#SBATCH -c 8
#SBATCH -t 0-12:00
#SBATCH --mem=25G
#SBATCH -p short
#SBATCH -o GoldenDelicious_%j.out
#SBATCH --mail-type=NONE
#SBATCH --mail-user=chong.simonchu@gmail.com
PREFIX=/powerplant/workspace/hrakws/xTea_test/xTea/outputs/GoldenDelicious/Alu/
############
############
ANNOTATION=/powerplant/workspace/hrakws/xTea_test/xTea/rep_lib_annotation_outputs/Alu/hg38/hg38_Alu.out
ANNOTATION1=/powerplant/workspace/hrakws/xTea_test/xTea/rep_lib_annotation_outputs/Alu/hg38/hg38_Alu.out
REF=/powerplant/input/genomic/plant/Malus/Genome/GDDH13_v1.1/Decompress/GDDH13_1-1_formatted.fasta
GENE=/powerplant/input/genomic/plant/Malus/Genome/GDDH13_v1.1/Decompress/gene_annotation_formatee.gff3
BLACK_LIST=null
L1_COPY_WITH_FLANK=/powerplant/workspace/hrakws/xTea_test/xTea/rep_lib_annotation_outputs/Alu/hg38/hg38_AluJabc_copies_with_flank.fa
SF_FLANK=null
L1_CNS=/powerplant/workspace/hrakws/xTea_test/xTea/rep_lib_annotation_outputs/consensus/ALU.fa
XTEA_PATH=/powerplant/workspace/hrakws/xTea_test/xTea/xtea/
BAM_LIST=${PREFIX}"bam_list.txt"
BAM1=${PREFIX}"10X_phased_possorted_bam.bam"
BARCODE_BAM=${PREFIX}"10X_barcode_indexed.sorted.bam"
TMP=${PREFIX}"tmp/"
TMP_CLIP=${PREFIX}"tmp/clip/"
TMP_CNS=${PREFIX}"tmp/cns/"
TMP_TNSD=${PREFIX}"tmp/transduction/"
############
############
python ${XTEA_PATH}"x_TEA_main.py" -C -i ${BAM_LIST} --lc 3 --rc 3 --cr 1  -r ${L1_COPY_WITH_FLANK}  -a ${ANNOTATION} --cns ${L1_CNS} --ref ${REF} -p ${TMP} -o ${PREFIX}"candidate_list_from_clip.txt"  -n 8 --cp /powerplant/workspace/hrakws/xTea_test/xTea/outputs/GoldenDelicious/pub_clip/     
python ${XTEA_PATH}"x_TEA_main.py"  -D -i ${PREFIX}"candidate_list_from_clip.txt" --nd 5 --ref ${REF} -a ${ANNOTATION} -b ${BAM_LIST} -p ${TMP} -o ${PREFIX}"candidate_list_from_disc.txt" -n 8    
python ${XTEA_PATH}"x_TEA_main.py" -N --cr 3 --nd 5 -b ${BAM_LIST} -p ${TMP_CNS} --fflank ${SF_FLANK} --flklen 3000 -n 8 -i ${PREFIX}"candidate_list_from_disc.txt" -r ${L1_CNS} --ref ${REF} -a ${ANNOTATION} -o ${PREFIX}"candidate_disc_filtered_cns.txt"    
python ${XTEA_PATH}"x_TEA_main.py" --transduction --cr 3 --nd 5 -b ${BAM_LIST} -p ${TMP_TNSD} --fflank ${SF_FLANK} --flklen 3000 -n 8 -i ${PREFIX}"candidate_disc_filtered_cns.txt" -r ${L1_CNS} --ref ${REF} --input2 ${PREFIX}"candidate_list_from_disc.txt.clip_sites_raw_disc.txt" --rtype 2 -a ${ANNOTATION1}    -o ${PREFIX}"candidate_disc_filtered_cns2.txt"
python ${XTEA_PATH}"x_TEA_main.py" --sibling --cr 3 --nd 5 -b ${BAM_LIST} -p ${TMP_TNSD} --fflank ${SF_FLANK} --flklen 3000 -n 8 -i ${PREFIX}"candidate_disc_filtered_cns2.txt" -r ${L1_CNS} --ref ${REF} --input2 ${PREFIX}"candidate_list_from_disc.txt.clip_sites_raw_disc.txt" --rtype 2 -a ${ANNOTATION1} --blacklist ${BLACK_LIST}    -o ${PREFIX}"candidate_sibling_transduction2.txt"
python ${XTEA_PATH}"x_TEA_main.py" --postF --rtype 2 -p ${TMP_CNS} -n 8 -i ${PREFIX}"candidate_disc_filtered_cns2.txt" -a ${ANNOTATION1}   -o ${PREFIX}"candidate_disc_filtered_cns_post_filtering.txt"
python ${XTEA_PATH}"x_TEA_main.py" --postF --rtype 2 -p ${TMP_CNS} -n 8 -i ${PREFIX}"candidate_disc_filtered_cns2.txt.high_confident" -a ${ANNOTATION1} --blacklist ${BLACK_LIST}   -o ${PREFIX}"candidate_disc_filtered_cns.txt.high_confident.post_filtering.txt"
python ${XTEA_PATH}"x_TEA_main.py" --gene -a ${GENE} -i ${PREFIX}"candidate_disc_filtered_cns.txt.high_confident.post_filtering.txt"  -n 8 -o ${PREFIX}"candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene.txt"
python ${XTEA_PATH}"x_TEA_main.py" --gntp_classify -i ${PREFIX}"candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene.txt"  -n 1 --model ${XTEA_PATH}"genotyping/DF21_model_1_2"  -o ${PREFIX}"candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt"
python ${XTEA_PATH}"x_TEA_main.py" --gVCF -i ${PREFIX}"candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt"  -o ${PREFIX} -b ${BAM_LIST} --ref ${REF} --rtype 2
python ${XTEA_PATH}"x_TEA_main.py" --igv --single_sample -p ${PREFIX}"tmp/igv" -b ${PREFIX}"bam_list1.txt" -i ${PREFIX}"candidate_disc_filtered_cns.txt"  --ref ${REF} -e 1000 -n 8 -o ${PREFIX}"tmp/igv/bamsnap_screenshot.txt"
python ${XTEA_PATH}"x_TEA_main.py" --igv --single_sample -p ${PREFIX}"tmp/igv" -b ${PREFIX}"bam_list1.txt" -i ${PREFIX}"candidate_disc_filtered_cns.txt.high_confident.post_filtering.txt"  --ref ${REF} -e 1000 -n 8 -o ${PREFIX}"tmp/igv/bamsnap_screenshot_hc.txt"
```

**Comment by simoncchu** [comment]
All the commands look good to me. I am not sure where the error was triggered... Are you working on non-human species? Looks like you are working on apple genome. All the annotation files are for human only. Maybe this is the reason.

**Comment by hzlnutspread** [comment]
yes @simoncchu this is a plant genome. Is there another way to use the annotation files for plant and not human?

**Comment by simoncchu** [comment]
@hzlnutspread you can try https://github.com/parklab/xTea/issues/20

**Comment by dongjuleem** [comment]
> yes, please remove this option. It doesn't affect the results.

Hello. thanks for great tools. I'm leaving a reply because I want to confirm if I understand correctly. 
After running `sh run_gnrt_pipeline.sh`, should I remove the options specified for **--bamsnap** in L1, Alu, SVA/run_xTEA_pipeline.sh?

**Comment by simoncchu** [comment]
You can keep it, although it may report some error, but the results will not be affected.
